name: store_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  readmore: ^2.1.0
  convex_bottom_bar: ^2.4.0
  dropdown_formfield: ^0.1.3
  email_validator: '^1.0.0'
  awesome_card: ^1.1.5
  credit_card_validator: ^2.0.0
  flutter:
    sdk: flutter
  carousel_pro: ^1.0.0
  modal_progress_hud: ^0.1.3
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  firebase_storage: ^7.0.0
  cloud_firestore: ^0.16.0
  flutter_typeahead: ^2.0.0
  image_picker: ^0.6.7+22
  flutter_rating_bar: ^4.0.0
  fluttertoast: ^8.0.7




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - icons/
  fonts:
    - family: Zanzabar
      fonts:
        - asset: fonts/Zanzabar D.otf
          weight: 700


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
